### ISSUE TITLE
Test cases failed with EI 6.2.0

### ISSUE THREAD

**Issue by Nirthika** [wso2-extensions/esb-connector-snmp#5]
**Description:**
Failed tests:   testSnmpSetWithMandatoryParameters(org.wso2.carbon.connector.integration.test.snmp.SnmpConnectorIntegrationTest): expected:<200> but was:<202>

**Comment by keerthu** [comment]
Fixed in https://github.com/wso2-extensions/esb-connector-snmp/pull/4
